#!/bin/bash
# Hook: Block edits to the SAVE_CONFIG block in Klipper printer.cfg files.
# The SAVE_CONFIG block is auto-generated by Klipper and must not be manually edited.

INPUT="$CLAUDE_TOOL_INPUT"

# Only check .cfg files
FILE=$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('file_path',''))" 2>/dev/null)
if [ -z "$FILE" ]; then
  exit 0
fi
case "$FILE" in
  *.cfg) ;;
  *) exit 0 ;;
esac

# Check old_string (Edit tool) and content (Write tool) for SAVE_CONFIG references
OLD_STRING=$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('old_string',''))" 2>/dev/null)
NEW_STRING=$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('new_string',''))" 2>/dev/null)
CONTENT=$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('content',''))" 2>/dev/null)

if echo "$OLD_STRING" | grep -qi "SAVE_CONFIG"; then
  echo "BLOCKED: Do not edit the SAVE_CONFIG block. It is auto-generated by Klipper (PID values, probe offsets, bed mesh). Manual edits will be overwritten or break Klipper." >&2
  exit 2
fi

if echo "$CONTENT" | grep -qi "SAVE_CONFIG"; then
  echo "BLOCKED: Do not overwrite a file containing the SAVE_CONFIG block. That section is auto-generated by Klipper." >&2
  exit 2
fi

exit 0
